### ISSUE TITLE
SubgradientSSVM trained with n_jobs > 1 performing worse than SubgradientSSVM trained with n_jobs==1 after same number of iterations

### ISSUE THREAD

**Issue by robbymeals** [pystruct/pystruct#134]
writing some tests for SaveLogger functionality with n_jobs > 1, because currently my pool attribute causes this to fail, and came across what I think is a bug.
Significant differences in performance for SubgradientSSVM between training with n_jobs==1 and n_jobs > 1, in current code using Parallel. I haven't tested whether Pool implementation is not showing this behavior. Seems worse with more cores:

on my local machine, 4 cores:
```
local$ python subgradient_ssvm_bug.py
0.973684210526
0.921052631579
```

on aws server, 16 cores:
```
aws-server$ python subgradient_ssvm_bug.py
0.973684210526
0.710526315789
```
```python
import numpy as np
from sklearn.datasets import load_iris
from sklearn.cross_validation import train_test_split
from pystruct.models import GraphCRF
from pystruct.learners import SubgradientSSVM

if __name__ == '__main__':
    iris = load_iris()
    X, y = iris.data, iris.target

    X_ = [(np.atleast_2d(x), np.empty((0, 2), dtype=np.int)) for x in X]
    Y = y.reshape(-1, 1)

    X_train, X_test, y_train, y_test = train_test_split(X_, Y, random_state=1)

    pbl = GraphCRF(n_features=4, n_states=3, inference_method='unary')

    svm = SubgradientSSVM(pbl, max_iter=100)
    svm.fit(X_train, y_train)
    print svm.score(X_test, y_test)

    svm_par = SubgradientSSVM(pbl, max_iter=100, n_jobs=-1)
    svm_par.fit(X_train, y_train)
    print svm_par.score(X_test, y_test)
```

**Comment by amueller** [comment]
Not really a bug, but maybe an non-obvious feature.
The ``max_iter`` says how many times you will go through the dataset. If you set n_jobs > 1, this will result in minibatches, which means less weight updates per iteration. If you set ``max_iter`` to ``n_cpus * 100`` it will (hopefully) outperform the other version.
I don't know if there is another or better way to do this.

**Comment by robbymeals** [comment]
Ah yeah I get it. Yeah, changing `max_iter` to `n_cpus * 100` far outperforms actually. Ok I'll close it.
