### ISSUE TITLE
inference_dispatch() for segmentation mask regularization

### ISSUE THREAD

**Issue by conze** [pystruct/pystruct#156]
Hi, 
I'm trying to use inference_dispatch() to regularize a segmentation mask obtained with Random Forest. My unary term deals with Random Forest output probabilities but my question is : how can we tune pairwise potentials to get a good balance between both terms ? np.eye() as in the example online does not provide good results. 
Moreover, can we see the energy value for each entity (unary + pairwise potentials) ? 
Is there any more complete documentation on how it works ? 
Thank you for your answer !

**Comment by amueller** [comment]
Have you looked at this example?
http://pystruct.github.io/auto_examples/plot_potts_model.html
What do you mean by energy values for each entity? You can multiply the eye matrix by a scalar to change the strength.

**Comment by conze** [comment]
The eye matrix works well in your example. For my test (where unaries are probabilities between 0 and 1), it does not. I have tried to multiply the eye matrix by a scalar but the output is very sensitive to this parameter and each new image requires to tune it ! Is there a way to avoid it ? By "energy values for each entity" i mean "sum of unary and pairwise terms for each node in the graph" ? I need this info to tune the scalar value ! 
Moreover, in my program, each node (corresponds to cluster in my case) is link to a various number of neighbors. Do I have to normalize pairwise by the number of neighbors ? 
Thank you !

**Comment by amueller** [comment]
Whether you need to normalize depends on your problem. You should try, 
though.
Do you have ground truth for you data? Then you can just use pystruct to 
learn the parameters / do the tuning for you.
I'm not sure how you want to visualize the pairwise terms. You could do 
that for a given assignment of the variables, but I'm not sure
how helpful this will be.

**Comment by amueller** [comment]
closing as no feedback and question not issue.
