### ISSUE TITLE
manually save model through SaveLogger?

### ISSUE THREAD

**Issue by shengshuyang** [pystruct/pystruct#162]
I couldn't find an API like `SaveLogger.save()` that saves current trained model manually. According to the documentation, `SaveLogger` can only be passed to a training algorithm and save models automatically, however, it's not uncommon that we stop and debug and like to save an extra copy of the model to other places.

**Comment by amueller** [comment]
I would just use pickle directly in that cases. But then you'd need to manually enter the path.
I'd suggest changing the ``__call__`` method, so that if you pass it any string, it just saves with this postfix to the file (currently it only checks for ``"final"``).
PR welcome

**Comment by amueller** [comment]
(sorry misclick)
