### ISSUE TITLE
Anaconda install instructions don't work 

### ISSUE THREAD

**Issue by scramblingbalam** [pystruct/pystruct#199]
The installation instructions found at
[https://pystruct.github.io/installation.html#installation](url)
doesn't work
I found a built package on the Anaconda cloud at
[https://anaconda.org/omnia/cvxopt](url)
and the command line
`conda install -c omnia cvxopt=1.1.8`
seems to have worked

The actual install of pyStruct failed though at least form
[https://anaconda.org/pypi/pystruct](url)
I tried 
`pip install -i https://pypi.anaconda.org/pypi/simple pystruct`
&
`pip install pystruct`
and I got this commandline output, I'm using windows 10
`
PS C:\Users\scram> pip install -i https://pypi.anaconda.org/pypi/simple pystruct
Collecting pystruct
  Downloading https://pypi.anaconda.org/pypi/simple/pystruct/0.2/pystruct-0.2.tar.gz (5.5MB)
    100% |################################| 5.5MB 211kB/s
Collecting ad3 (from pystruct)
  Downloading https://pypi.anaconda.org/pypi/simple/ad3/2.0/ad3-2.0.tar.gz (518kB)
    100% |################################| 522kB 644kB/s
Collecting pyqpbo (from pystruct)
  Downloading https://pypi.anaconda.org/pypi/simple/pyqpbo/0.1/pyqpbo-0.1.tar.gz (76kB)
    100% |################################| 81kB 487kB/s
Building wheels for collected packages: pystruct, ad3, pyqpbo
  Running setup.py bdist_wheel for pystruct ... error
  Complete output from command C:\Anaconda\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\scram\\app
data\\local\\temp\\pip-build-y7webf\\pystruct\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().repla
ce('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\scram\appdata\local\temp\tmpox
rjdvpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-2.7
  creating build\lib.win-amd64-2.7\pystruct
  copying pystruct\plot_learning.py -> build\lib.win-amd64-2.7\pystruct
  copying pystruct\__init__.py -> build\lib.win-amd64-2.7\pystruct
  creating build\lib.win-amd64-2.7\pystruct\learners
  copying pystruct\learners\downhill_simplex_ssvm.py -> build\lib.win-amd64-2.7\pystruct\learners
  copying pystruct\learners\frankwolfe_ssvm.py -> build\lib.win-amd64-2.7\pystruct\learners
  copying pystruct\learners\latent_structured_svm.py -> build\lib.win-amd64-2.7\pystruct\learners
  copying pystruct\learners\n_slack_ssvm.py -> build\lib.win-amd64-2.7\pystruct\learners
  copying pystruct\learners\one_slack_ssvm.py -> build\lib.win-amd64-2.7\pystruct\learners
  copying pystruct\learners\ssvm.py -> build\lib.win-amd64-2.7\pystruct\learners
  copying pystruct\learners\structured_perceptron.py -> build\lib.win-amd64-2.7\pystruct\learners
  copying pystruct\learners\subgradient_latent_ssvm.py -> build\lib.win-amd64-2.7\pystruct\learners
  copying pystruct\learners\subgradient_ssvm.py -> build\lib.win-amd64-2.7\pystruct\learners
  copying pystruct\learners\svm.py -> build\lib.win-amd64-2.7\pystruct\learners
  copying pystruct\learners\__init__.py -> build\lib.win-amd64-2.7\pystruct\learners
  creating build\lib.win-amd64-2.7\pystruct\inference
  copying pystruct\inference\inference_methods.py -> build\lib.win-amd64-2.7\pystruct\inference
  copying pystruct\inference\linear_programming.py -> build\lib.win-amd64-2.7\pystruct\inference
  copying pystruct\inference\__init__.py -> build\lib.win-amd64-2.7\pystruct\inference
  creating build\lib.win-amd64-2.7\pystruct\models
  copying pystruct\models\base.py -> build\lib.win-amd64-2.7\pystruct\models
  copying pystruct\models\chain_crf.py -> build\lib.win-amd64-2.7\pystruct\models
  copying pystruct\models\crf.py -> build\lib.win-amd64-2.7\pystruct\models
  copying pystruct\models\edge_feature_graph_crf.py -> build\lib.win-amd64-2.7\pystruct\models
  copying pystruct\models\graph_crf.py -> build\lib.win-amd64-2.7\pystruct\models
  copying pystruct\models\grid_crf.py -> build\lib.win-amd64-2.7\pystruct\models
  copying pystruct\models\latent_graph_crf.py -> build\lib.win-amd64-2.7\pystruct\models
  copying pystruct\models\latent_grid_crf.py -> build\lib.win-amd64-2.7\pystruct\models
  copying pystruct\models\latent_node_crf.py -> build\lib.win-amd64-2.7\pystruct\models
  copying pystruct\models\multilabel_svm.py -> build\lib.win-amd64-2.7\pystruct\models
  copying pystruct\models\setup.py -> build\lib.win-amd64-2.7\pystruct\models
  copying pystruct\models\unstructured_svm.py -> build\lib.win-amd64-2.7\pystruct\models
  copying pystruct\models\__init__.py -> build\lib.win-amd64-2.7\pystruct\models
  creating build\lib.win-amd64-2.7\pystruct\utils
  copying pystruct\utils\backports.py -> build\lib.win-amd64-2.7\pystruct\utils
  copying pystruct\utils\graph.py -> build\lib.win-amd64-2.7\pystruct\utils
  copying pystruct\utils\inference.py -> build\lib.win-amd64-2.7\pystruct\utils
  copying pystruct\utils\logging.py -> build\lib.win-amd64-2.7\pystruct\utils
  copying pystruct\utils\plotting.py -> build\lib.win-amd64-2.7\pystruct\utils
  copying pystruct\utils\__init__.py -> build\lib.win-amd64-2.7\pystruct\utils
  creating build\lib.win-amd64-2.7\pystruct\datasets
  copying pystruct\datasets\dataset_loaders.py -> build\lib.win-amd64-2.7\pystruct\datasets
  copying pystruct\datasets\synthetic_grids.py -> build\lib.win-amd64-2.7\pystruct\datasets
  copying pystruct\datasets\__init__.py -> build\lib.win-amd64-2.7\pystruct\datasets
  creating build\lib.win-amd64-2.7\pystruct\tests
  copying pystruct\tests\test_datasets.py -> build\lib.win-amd64-2.7\pystruct\tests
  copying pystruct\tests\test_libraries.py -> build\lib.win-amd64-2.7\pystruct\tests
  copying pystruct\tests\__init__.py -> build\lib.win-amd64-2.7\pystruct\tests
  creating build\lib.win-amd64-2.7\pystruct\tests\test_learners
  copying pystruct\tests\test_learners\test_binary_svm.py -> build\lib.win-amd64-2.7\pystruct\tests\test_learners
  copying pystruct\tests\test_learners\test_crammer_singer_svm.py -> build\lib.win-amd64-2.7\pystruct\tests\test_learner
s
  copying pystruct\tests\test_learners\test_edge_feature_graph_learning.py -> build\lib.win-amd64-2.7\pystruct\tests\tes
t_learners
  copying pystruct\tests\test_learners\test_frankwolfe_svm.py -> build\lib.win-amd64-2.7\pystruct\tests\test_learners
  copying pystruct\tests\test_learners\test_graph_svm.py -> build\lib.win-amd64-2.7\pystruct\tests\test_learners
  copying pystruct\tests\test_learners\test_latent_node_crf_learning.py -> build\lib.win-amd64-2.7\pystruct\tests\test_l
earners
  copying pystruct\tests\test_learners\test_latent_svm.py -> build\lib.win-amd64-2.7\pystruct\tests\test_learners
  copying pystruct\tests\test_learners\test_n_slack_ssvm.py -> build\lib.win-amd64-2.7\pystruct\tests\test_learners
  copying pystruct\tests\test_learners\test_one_slack_ssvm.py -> build\lib.win-amd64-2.7\pystruct\tests\test_learners
  copying pystruct\tests\test_learners\test_perceptron.py -> build\lib.win-amd64-2.7\pystruct\tests\test_learners
  copying pystruct\tests\test_learners\test_primal_dual.py -> build\lib.win-amd64-2.7\pystruct\tests\test_learners
  copying pystruct\tests\test_learners\test_structured_perceptron.py -> build\lib.win-amd64-2.7\pystruct\tests\test_lear
ners
  copying pystruct\tests\test_learners\test_subgradient_latent_svm.py -> build\lib.win-amd64-2.7\pystruct\tests\test_lea
rners
  copying pystruct\tests\test_learners\test_subgradient_svm.py -> build\lib.win-amd64-2.7\pystruct\tests\test_learners
  copying pystruct\tests\test_learners\__init__.py -> build\lib.win-amd64-2.7\pystruct\tests\test_learners
  creating build\lib.win-amd64-2.7\pystruct\tests\test_models
  copying pystruct\tests\test_models\test_chain_crf.py -> build\lib.win-amd64-2.7\pystruct\tests\test_models
  copying pystruct\tests\test_models\test_directional_crf.py -> build\lib.win-amd64-2.7\pystruct\tests\test_models
  copying pystruct\tests\test_models\test_edge_feature_graph_crf.py -> build\lib.win-amd64-2.7\pystruct\tests\test_model
s
  copying pystruct\tests\test_models\test_graph_crf.py -> build\lib.win-amd64-2.7\pystruct\tests\test_models
  copying pystruct\tests\test_models\test_grid_crf.py -> build\lib.win-amd64-2.7\pystruct\tests\test_models
  copying pystruct\tests\test_models\test_latent_crf.py -> build\lib.win-amd64-2.7\pystruct\tests\test_models
  copying pystruct\tests\test_models\test_latent_node_crf.py -> build\lib.win-amd64-2.7\pystruct\tests\test_models
  copying pystruct\tests\test_models\test_multilabel_problem.py -> build\lib.win-amd64-2.7\pystruct\tests\test_models
  copying pystruct\tests\test_models\__init__.py -> build\lib.win-amd64-2.7\pystruct\tests\test_models
  creating build\lib.win-amd64-2.7\pystruct\tests\test_inference
  copying pystruct\tests\test_inference\test_exact_inference.py -> build\lib.win-amd64-2.7\pystruct\tests\test_inference
  copying pystruct\tests\test_inference\__init__.py -> build\lib.win-amd64-2.7\pystruct\tests\test_inference
  creating build\lib.win-amd64-2.7\pystruct\tests\test_utils
  copying pystruct\tests\test_utils\test_utils_inference.py -> build\lib.win-amd64-2.7\pystruct\tests\test_utils
  copying pystruct\tests\test_utils\__init__.py -> build\lib.win-amd64-2.7\pystruct\tests\test_utils
  running egg_info
  writing requirements to pystruct.egg-info\requires.txt
  writing pystruct.egg-info\PKG-INFO
  writing top-level names to pystruct.egg-info\top_level.txt
  writing dependency_links to pystruct.egg-info\dependency_links.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'pystruct.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*' under directory 'tests'
  warning: no previously-included files matching '*.pyc' found under directory 'doc'
  warning: no previously-included files matching '*.pyo' found under directory 'doc'
  warning: no previously-included files matching '*.pyc' found under directory 'tests'
  warning: no previously-included files matching '*.pyo' found under directory 'tests'
  no previously-included directories found matching 'docs\_build'
  no previously-included directories found matching 'docs\auto_examples'
  no previously-included directories found matching 'docs\generated'
  writing manifest file 'pystruct.egg-info\SOURCES.txt'
  copying pystruct\datasets\letters.pickle -> build\lib.win-amd64-2.7\pystruct\datasets
  copying pystruct\datasets\scene.pickle -> build\lib.win-amd64-2.7\pystruct\datasets
  copying pystruct\datasets\snakes.pickle -> build\lib.win-amd64-2.7\pystruct\datasets
  running build_ext
  skipping 'src\utils.c' Cython extension (up-to-date)
  building 'pystruct.models.utils' extension
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\Release
  creating build\temp.win-amd64-2.7\Release\src
  gcc -DMS_WIN64 -mdll -O -Wall -IC:\Anaconda\include -IC:\Anaconda\PC -c src\utils.c -o build\temp.win-amd64-2.7\Releas
e\src\utils.o
  error: command 'gcc' failed: No such file or directory

  ----------------------------------------
  Failed building wheel for pystruct
  Running setup.py clean for pystruct
  Running setup.py bdist_wheel for ad3 ... error
  Complete output from command C:\Anaconda\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\scram\\app
data\\local\\temp\\pip-build-y7webf\\ad3\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\
r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\scram\appdata\local\temp\tmpq8ytncp
ip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-2.7
  creating build\lib.win-amd64-2.7\ad3
  copying python\ad3\simple_inference.py -> build\lib.win-amd64-2.7\ad3
  copying python\ad3\__init__.py -> build\lib.win-amd64-2.7\ad3
  running build_clib
  building 'ad3' library
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\ad3
  gcc -DMS_WIN64 -mdll -O -Wall -I. -I./ad3 -I./Eigen -c ad3/FactorGraph.cpp -o build\temp.win-amd64-2.7\ad3\factorgraph
.o
  error: command 'gcc' failed: No such file or directory

  ----------------------------------------
  Failed building wheel for ad3
  Running setup.py clean for ad3
  Running setup.py bdist_wheel for pyqpbo ... error
  Complete output from command C:\Anaconda\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\scram\\app
data\\local\\temp\\pip-build-y7webf\\pyqpbo\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace
('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\scram\appdata\local\temp\tmpecet
a3pip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-2.7
  creating build\lib.win-amd64-2.7\pyqpbo
  copying pyqpbo\__init__.py -> build\lib.win-amd64-2.7\pyqpbo
  running build_ext
  building 'pyqpbo.pyqpbo' extension
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\Release
  creating build\temp.win-amd64-2.7\Release\src
  creating build\temp.win-amd64-2.7\Release\qpbo-v1.3.src
  gcc -DMS_WIN64 -mdll -O -Wall -IQPBO-v1.3.src -IC:\Anaconda\lib\site-packages\numpy\core\include -IC:\Anaconda\include
 -IC:\Anaconda\PC -c src/pyqpbo.cpp -o build\temp.win-amd64-2.7\Release\src\pyqpbo.o -fpermissive
  error: command 'gcc' failed: No such file or directory

  ----------------------------------------
  Failed building wheel for pyqpbo
  Running setup.py clean for pyqpbo
Failed to build pystruct ad3 pyqpbo
Installing collected packages: ad3, pyqpbo, pystruct
  Running setup.py install for ad3 ... error
    Complete output from command C:\Anaconda\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\scram\\a
ppdata\\local\\temp\\pip-build-y7webf\\ad3\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace(
'\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\scram\appdata\local\temp\pip-86
moab-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\ad3
    copying python\ad3\simple_inference.py -> build\lib.win-amd64-2.7\ad3
    copying python\ad3\__init__.py -> build\lib.win-amd64-2.7\ad3
    running build_clib
    building 'ad3' library
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\ad3
    gcc -DMS_WIN64 -mdll -O -Wall -I. -I./ad3 -I./Eigen -c ad3/FactorGraph.cpp -o build\temp.win-amd64-2.7\ad3\factorgra
ph.o
    error: command 'gcc' failed: No such file or directory

    ----------------------------------------
Command "C:\Anaconda\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\scram\\appdata\\local\\temp\\pip
-build-y7webf\\ad3\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();
exec(compile(code, __file__, 'exec'))" install --record c:\users\scram\appdata\local\temp\pip-86moab-record\install-reco
rd.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\scram\appdata\local\temp\pip-
build-y7webf\ad3\`

**Comment by scramblingbalam** [comment]
used 
`conda install mingw`
and 
`pip install -i https://pypi.anaconda.org/pypi/simple pystruct`
install didn't fail but the 
`conda install -c omnia cvxopt=1.1.8`
doesn't work with Anaconda, it was a little stupid to think it would but I wasn't aware that Omnia was a python distrubution

**Comment by scramblingbalam** [comment]
Reinstalled Anaconda because of problems getting graphviz to work 
So I have to reinstall PyStruct, didn't not think about this...

**Comment by amueller** [comment]
It's a bit strange to install via pip from the anaconda mirror... why not from pip directly?
I'm not sure what the omnia is. You need a compiler to compile pystruct, I guess the mingw installs gcc.
Feel free to reopen if you're still having issues, sorry for the slow reply.
