### ISSUE TITLE
Can we use this to classify text? 

### ISSUE THREAD

**Issue by jamesalcatraz** [pystruct/pystruct#204]
All examples here are for image classification. I want to do some document/text classification using this with a word2vec embedding and a crf model.  What combination of model and learner to use if possible?

**Comment by amueller** [comment]
Sorry for the slow reply. None of the examples do image classification. They do image segmentation or tagging. You can not really use pystruct for classification. You could use it for named entity recognition or POS tagging etc. Feel free to reopen.
