### ISSUE TITLE
'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by AleksaT** [pystruct/pystruct#211]
Hi,
When I call the method fit() I got an error like this
```
File "C:\\Python\Python35\site-packages\pystruct\learners\frankwolfe_ssvm.py", line 291, in fit
    self.w = getattr(self, "w", np.zeros(int(self.model.size_joint_feature)))

TypeError: 'float' object cannot be interpreted as an integer
```
I get this error for any learner.
I hope someone knows how to solve this :)

Thanks!

**Comment by amueller** [comment]
can you please provide code to reproduce? Or did you figure it out?

**Comment by amueller** [comment]
It's probably y being float while pystruct only supports int?

**Comment by jlmeunier** [comment]
Hi, we have fixed this in the newest version. Thanks for the report anyway!
