### ISSUE TITLE
Why i ran example code in my pc it gives error like 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by ANUBHAVNATANI** [pystruct/pystruct#222]
I tried running all the crf examples given in docs all gave me this same error.

**Comment by jlmeunier** [comment]
Hi,
which version are you using? (of Python and of pystruct)
I would guess you have python3 and pystruct 0.2.x
WIth python3, please get the source from github and do a python setup.py install.

**Comment by ANUBHAVNATANI** [comment]
i tried that but it give the same error.
                        17 latent_svm.fit(X_train, y_train)
Error is in line  82 w = np.zeros(self.model.size_joint_feature)
TypeError: 'numpy.float64' object cannot be interpreted as an integer
