### ISSUE TITLE
website: fix links to classes in examples

### ISSUE THREAD

**Issue by amueller** [pystruct/pystruct#65]
There is this fancy script that creates links for all classes and functions in the examples to the documentation.
In scikit-learn that works for classes, in pystruct it doesn't :-/

**Comment by ryneeverett** [comment]
This issue seems to have arisen again.

**Comment by ryneeverett** [comment]
Huh, it generates [this page](http://pystruct.github.io/_modules/) but all the links are dead.

**Comment by ryneeverett** [comment]
Oh, my bad, I'm looking at the `[source]` links on the doc pages, not the links *to* the doc pages. This is a separate issue.

**Comment by amueller** [comment]
Sorry, I'm not sure what your issue is.

**Comment by ryneeverett** [comment]
It's not a big deal, but the `[source]` links created by `sphinx.ext.viewcode` next to each class in the reference API return 404's. [Example](http://pystruct.github.io/generated/pystruct.models.BinaryClf.html#pystruct.models.BinaryClf). As you can see the [_modules](http://pystruct.github.io/_modules/) links are all dead. I ran the sphinx build locally and the _modules pages are successfully created so I wonder if it's a bug in the docs deployment process (perhaps ignoring directories named `pystruct`?).

**Comment by amueller** [comment]
Ah. Yeah probably a mistake on my part uploading the website. I'll open a new issue for it.
